language: csharp
solution: LdapManager.sln

dotnet: 2.1
mono: none

install:
  - dotnet restore LdapManager.sln
script:
  - dotnet build 
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success: 
  - dotnet tool install coveralls.net --version 1.0.0 --tool-path tools/coveralls
  - ./tools/coveralls/csmacnz.Coveralls --opencover -i ./LdapManager.Test/coverage.opencover.xml --repoToken "$coverallToken"