language: csharp
solution: LdapUserManager.sln

dotnet: 2.2
mono: none

install:
  - dotnet restore LdapUserManager.sln
script:
  - dotnet build 
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_success: 
  - ./tools/csmacnz.Coveralls --opencover -i ./LdapUserManager.Test/coverage.opencover.xml --repoToken "$coverallToken"