language: csharp
solution: LdapUserManager.sln

dotnet: 2.2
mono: none

install:
  - dotnet restore LdapUserManager.sln
script:
  - dotnet build
  - cd minicover
  - dotnet minicover instrument --workdir ../ --assemblies LdapUserManager.Test/**/bin/**/*.dll --sources LdapUserManager/**/*.cs 
  - dotnet minicover reset
  - dotnet minicover coverallsreport --root-path ../ --workdir ../ --repo-token "$coverallToken"
